plan:
    package: ./ci
name: ci
inputs:
    source:
        dir:
            path: .
            exclude:
                - node_modules
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a6fwn2y4c2d9k3wt39cfq6myxcqqjscq7kq245fj7lvkhkf29dhqt62kmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQWJlelc4ZFJzTGJzNHIr
            Nm9EMTk5anFPMDAvWnhySDB3cU9sNHV0ZUN3CmdWcHJDemd2LzI5RWpKNCs4Vm4w
            UVJRRHp0S2FVcjdiMmZtK1dEWmxPczgKLS0tIEtib1UyV05JR3lFQ25BeEhMekFZ
            cG03dUtUYU90YTlob0FoT2FYUEZuTEUKzYjEdY1s6Q1dq+6TdornaWFdOyE+/Dne
            iPmZM3QjTM29vJAidRY5KLVI8lmW+4Bz4Mks0+me96wdsWQLlMK3oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-11T03:07:52Z"
    mac: ENC[AES256_GCM,data:/3N8+UxXQJCuSE8m7nFYZJbJC3cgHR/2FNohkSZdlErDgvLtFSO/1W3n/K1jeV/tjzQXiXiJoP2d6iGq7I5Ah+CQkJgRJwxik9vHyxyBERoCA8TSaIe8CucUJzG7XhQxlpMiiIgmEyrpQbuQ+sZQM2UcE4xorUTF15DBECj+P4w=,iv:hkb/8x0m75F8gtpKKdezdkmG03A3jo8vqPBvo1bQEKM=,tag:RMr1XLHnJPdTI43McSaMqQ==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
