name: Tests
on: 
  push:
    branches:
      - next
  pull_request:
    branches: 
      - next
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Install Dagger
        uses: dagger/dagger-action@v1
        # https://github.com/dagger/dagger-action/pull/17
        with:    
          install-only: true
      - name: Up
        run: >
          mkdir -p ~/.config/dagger && 
          echo ${{ secrets.DAGGER_AGE_KEY }} > ~/.config/dagger/keys.txt &&
          dagger up --environment ci
        
